### ISSUE TITLE
Not working OK with Bootstrap 

### ISSUE THREAD

**Issue by dmarcos89** [steffest/PatternLock#1] opened 2015-08-05 03:16 UTC
Hi, do u have any idea why it´s broken when using bootstrap?

![captura de pantalla 2015-08-05 a las 0 14 59](https://cloud.githubusercontent.com/assets/6944569/9077659/14f2974c-3b07-11e5-9560-0e53b8dd4131.png)

Thanks!!

**Comment by steffest** [comment] 2015-09-07 11:37
This is caused by the box-sizing CSS in bootstrap.
It is fixed in e9144e6813553823fad142e01de77ceb6afdb2cb

**Closed as completed by steffest** 2015-09-07 11:37 UTC

**Comment by mrdidie** [comment] 2016-12-17 17:05
Hi, I have no idea how to loop  the function on patternlock.js. I want user can draw-pattern 4 times before they can submit the 'value' of the result. So, I already try and make changes to that code, but am failed. In which part we can loop JS function to ask user to draw 4 times pattern?
